name: List releases

on:
  workflow_dispatch:

jobs:
  list_releases_contents_read:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release list --json name | cat

  list_releases_contents_write:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release list --json name | cat
